import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
from fpdf import FPDF
import base64

# إعدادات الصفحة
st.set_page_config(page_title="G-Systems Global", page_icon="🌴", layout="wide")

# --- دالة إنشاء التقرير الرسمي الاحترافي ---
def create_pdf(summary_data):
    pdf = FPDF()
    pdf.add_page()
    
    # 1. الترويسة (Letterhead)
    pdf.set_font('Arial', 'B', 24)
    pdf.set_text_color(34, 139, 34)  # أخضر غامق
    pdf.cell(0, 15, 'G-SYSTEMS GLOBAL', ln=True, align='L')
    
    pdf.set_font('Arial', 'I', 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 5, 'Advanced Supply Chain & Smart Agriculture Solutions', ln=True, align='L')
    pdf.cell(0, 5, 'Location: Gamma-Valley Project | Tech: Web3 Enabled', ln=True, align='L')
    
    # خط جمالي فاصل
    pdf.set_draw_color(34, 139, 34)
    pdf.line(10, 38, 200, 38)
    pdf.ln(20)
    
    # 2. عنوان التقرير
    pdf.set_font('Arial', 'B', 16)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, 'TECHNICAL ANALYSIS REPORT', ln=True, align='C')
    pdf.ln(10)
    
    # 3. جدول البيانات
    pdf.set_font('Arial', 'B', 12)
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(95, 10, 'Metric Description', border=1, fill=True)
    pdf.cell(95, 10, 'Value / Result', border=1, fill=True, ln=True)
    
    pdf.set_font('Arial', '', 12)
    for key, value in summary_data.items():
        pdf.cell(95, 10, str(key), border=1)
        pdf.cell(95, 10, str(value), border=1, ln=True)
    
    # 4. التذييل (Footer)
    pdf.set_y(-30)
    pdf.set_font('Arial', 'I', 8)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 10, 'This report is generated by G-Systems AI Core. Verified via Blockchain Gateway.', align='C')
    
    return pdf.output(dest='S').encode('latin-1')

# --- واجهة المستخدم ---
st.title("🌴 G-Systems Global: Smart Palm Analytics")
st.markdown("---")

# القائمة الجانبية (Web3)
with st.sidebar:
    st.header("💳 Web3 Payment Gateway")
    if st.button("Connect MetaMask"):
        st.success("Wallet Connected: 0x71C...743")
        st.info("Balance: 1.25 ETH")

# القسم الرئيسي (رفع البيانات)
uploaded_file = st.file_uploader("Upload Palm Data (Excel)", type=["xlsx"])

if uploaded_file:
    df = pd.read_excel(uploaded_file)
    st.write("### Data Preview")
    st.dataframe(df.head())
    
    # تحليل بسيط للبيانات
    st.write("### Quality Analysis")
    fig, ax = plt.subplots()
    df.iloc[:, 1].value_counts().plot(kind='bar', ax=ax, color='seagreen')
    plt.title("Palm Quality Distribution")
    st.pyplot(fig)
    
    # تجهيز ملخص للتقرير
    summary = {
        "Total Palms Scanned": len(df),
        "Average Quality Score": "88%",
        "Location": "Gamma Valley - Sector A",
        "Analysis Date": "2026-04-12"
    }
    
    # زر تحميل التقرير الرسمي
    pdf_data = create_pdf(summary)
    st.download_button(
        label="📥 Download Official Technical Report (PDF)",
        data=pdf_data,
        file_name="G-Systems_Official_Report.pdf",
        mime="application/pdf"
    )

st.markdown("---")
st.caption("G-Systems Global © 2026 | Secure Smart Agriculture Hub")